//! Identifier generation port traits.

use tssp_domain::{FileId, SessionToken};

use crate::errors::IdGenerationError;

/// Generates opaque identifiers used by the system.
pub trait IdGenerator {
    /// Returns a new file identifier.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when the generator cannot produce a valid
    /// unique identifier.
    fn new_file_id(&self) -> Result<FileId, IdGenerationError>;
}

/// Generates unguessable one-time transfer tokens.
pub trait SessionTokenGenerator {
    /// Returns a new 128-bit URL-safe session token.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when secure randomness is unavailable or
    /// generated bytes cannot be encoded into a valid token.
    fn new_session_token(&self) -> Result<SessionToken, IdGenerationError>;
}
