//! Boundary traits between application services and infrastructure.
//!
//! Implementations live in adapter crates. Keeping these traits small and typed
//! lets tests replace `SQLite`, filesystem storage, clocks, and ID generation with
//! deterministic in-memory doubles.

use std::fs::File;
use std::io::Read;
use std::sync::Arc;

use thiserror::Error;
use tssp_domain::{
    ContentHash, Cursor, FileId, FileName, FileRecord, FileSize, MimeType, SessionToken,
    StorageHandle, Tag, TagKey, UnixTimestamp,
};

/// Sort order for file listing queries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ListSort {
    /// Descending by upload timestamp (newest first). Default.
    #[default]
    UploadedDesc,
    /// Ascending by upload timestamp (oldest first).
    UploadedAsc,
    /// Ascending by filename.
    NameAsc,
    /// Descending by filename.
    NameDesc,
    /// Descending by file size.
    SizeDesc,
    /// Ascending by file size.
    SizeAsc,
}

impl ListSort {
    /// Parses a sort field string as produced by CLI `--sort` flag.
    ///
    /// A leading `-` negates the direction. Unknown fields return `None`.
    #[must_use]
    pub fn parse(value: &str) -> Option<Self> {
        match value.trim() {
            "uploaded" => Some(Self::UploadedAsc),
            "-uploaded" => Some(Self::UploadedDesc),
            "name" => Some(Self::NameAsc),
            "-name" => Some(Self::NameDesc),
            "size" => Some(Self::SizeAsc),
            "-size" => Some(Self::SizeDesc),
            _ => None,
        }
    }
}

/// Query parameters for filtered and paginated file listing.
#[derive(Debug, Clone)]
pub struct ListQuery {
    /// Maximum files to return. Must be between 1 and 500.
    pub limit: u64,
    /// Required tag keys (AND semantics). Empty means no tag filter.
    pub tags: Vec<TagKey>,
    /// MIME type prefix filter (`"image"` matches `"image/png"`).
    pub mime_prefix: Option<String>,
    /// Only return files uploaded at or after this timestamp.
    pub since: Option<UnixTimestamp>,
    /// Only return files uploaded at or before this timestamp.
    pub until: Option<UnixTimestamp>,
    /// When true, only pinned files are returned.
    pub pinned_only: bool,
    /// Sort order for the result.
    pub sort: ListSort,
    /// Opaque cursor from a previous response for the next page.
    pub after_cursor: Option<Cursor>,
}

impl Default for ListQuery {
    fn default() -> Self {
        Self {
            limit: 50,
            tags: Vec::new(),
            mime_prefix: None,
            since: None,
            until: None,
            pinned_only: false,
            sort: ListSort::UploadedDesc,
            after_cursor: None,
        }
    }
}

/// Paginated file listing result.
#[derive(Debug, Clone)]
pub struct PagedFiles {
    /// File records for the current page.
    pub files: Vec<FileRecord>,
    /// Cursor for the next page, absent when no further results exist.
    pub next_cursor: Option<Cursor>,
}

/// Result of a pin or unpin operation.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct PinOutcome {
    /// True when the file record exists.
    pub existed: bool,
    /// True when the pin state actually changed.
    pub changed: bool,
}

/// Supplies server-side UTC timestamps.
pub trait Clock {
    /// Returns the current UTC timestamp.
    fn now(&self) -> UnixTimestamp;
}

/// Generates opaque identifiers used by the system.
pub trait IdGenerator {
    /// Returns a new file identifier.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when the generator cannot produce a valid
    /// unique identifier.
    fn new_file_id(&self) -> Result<FileId, IdGenerationError>;
}

/// Generates unguessable one-time transfer tokens.
pub trait SessionTokenGenerator {
    /// Returns a new 128-bit URL-safe session token.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when secure randomness is unavailable or
    /// generated bytes cannot be encoded into a valid token.
    fn new_session_token(&self) -> Result<SessionToken, IdGenerationError>;
}

/// Stores and retrieves content-addressed blob bytes.
pub trait BlobStore {
    /// Streams bytes into storage and returns the durable content-addressed blob.
    ///
    /// # Errors
    ///
    /// Returns [`BlobStoreError`] when the source cannot be read or the storage
    /// backend cannot durably write the blob.
    fn put_stream(&self, source: &mut dyn Read) -> Result<BlobWriteOutcome, BlobStoreError>;

    /// Removes a blob that is not referenced by committed metadata.
    ///
    /// # Errors
    ///
    /// Returns [`BlobStoreError`] when cleanup cannot be completed. Callers
    /// should log this because it may require later orphan reclamation.
    fn cleanup_unreferenced(&self, handle: &StorageHandle) -> Result<(), BlobStoreError>;
}

/// Opens durable blob bytes for download.
pub trait BlobReader {
    /// Opens the blob identified by `handle`.
    ///
    /// # Errors
    ///
    /// Returns [`BlobReadError`] when the blob is missing or cannot be opened.
    fn open_blob(&self, handle: &StorageHandle) -> Result<File, BlobReadError>;
}

/// Persists and queries file metadata.
pub trait FileRepository {
    /// Inserts a logical file record for an already durable blob.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when metadata cannot be committed.
    fn insert_file(&self, new_file: NewFileRecord) -> Result<FileRecord, RepositoryError>;

    /// Returns one file record by id.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when metadata lookup fails.
    fn find_file(&self, id: &FileId) -> Result<Option<FileRecord>, RepositoryError>;

    /// Returns the oldest file record for a content hash.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when metadata lookup fails.
    fn find_file_by_content_hash(
        &self,
        content_hash: &ContentHash,
    ) -> Result<Option<FileRecord>, RepositoryError>;

    /// Deletes one logical file record and reports remaining blob references.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the delete transaction cannot complete.
    fn delete_file(&self, id: &FileId) -> Result<Option<DeletedFileRecord>, RepositoryError>;

    /// Returns recent files in descending order by upload time with an optional limit.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the query fails.
    fn list_files_recent(&self, limit: u64) -> Result<Vec<FileRecord>, RepositoryError>;

    /// Returns recent files containing a specific tag in descending order by upload time with an optional limit.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the query fails.
    fn list_files_by_tag(
        &self,
        tag: &TagKey,
        limit: u64,
    ) -> Result<Vec<FileRecord>, RepositoryError>;

    /// Returns all tags with committed file counts.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the query fails.
    fn list_tags(&self) -> Result<Vec<TagSummary>, RepositoryError>;

    /// Adds tags to an existing file idempotently.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError::NotFound`] when the file does not exist, or a
    /// repository failure when the mutation cannot be committed.
    fn add_tags_to_file(
        &self,
        id: &FileId,
        tags: &[Tag],
    ) -> Result<TagMutationOutcome, RepositoryError>;

    /// Removes one tag from an existing file idempotently.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError::NotFound`] when the file does not exist, or a
    /// repository failure when the mutation cannot be committed.
    fn remove_tag_from_file(
        &self,
        id: &FileId,
        tag: &TagKey,
    ) -> Result<TagMutationOutcome, RepositoryError>;

    /// Returns aggregate metadata counts for status reporting.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when aggregate queries fail.
    fn stats_since(&self, recent_since: UnixTimestamp) -> Result<RepositoryStats, RepositoryError>;

    /// Pins a file, optionally at a specific position.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError::NotFound`] if the file doesn't exist.
    fn pin_file(&self, id: &FileId, position: Option<u32>) -> Result<PinOutcome, RepositoryError>;

    /// Unpins a file.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError::NotFound`] if the file doesn't exist.
    fn unpin_file(&self, id: &FileId) -> Result<PinOutcome, RepositoryError>;

    /// Returns pinned files in pin order.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the query fails.
    fn list_pinned_files(&self) -> Result<Vec<FileRecord>, RepositoryError>;

    /// Reorders pins according to the provided list of file IDs.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the operation fails.
    fn reorder_pins(&self, ordered_ids: &[FileId]) -> Result<(), RepositoryError>;

    /// Searches files using full-text search.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when the search query fails.
    fn search_files(&self, query: &str) -> Result<Vec<FileRecord>, RepositoryError>;
}

impl<T> BlobStore for Arc<T>
where
    T: BlobStore,
{
    fn put_stream(&self, source: &mut dyn Read) -> Result<BlobWriteOutcome, BlobStoreError> {
        self.as_ref().put_stream(source)
    }

    fn cleanup_unreferenced(&self, handle: &StorageHandle) -> Result<(), BlobStoreError> {
        self.as_ref().cleanup_unreferenced(handle)
    }
}

impl<T> BlobReader for Arc<T>
where
    T: BlobReader,
{
    fn open_blob(&self, handle: &StorageHandle) -> Result<File, BlobReadError> {
        self.as_ref().open_blob(handle)
    }
}

impl<T> FileRepository for Arc<T>
where
    T: FileRepository,
{
    fn insert_file(&self, new_file: NewFileRecord) -> Result<FileRecord, RepositoryError> {
        self.as_ref().insert_file(new_file)
    }

    fn find_file(&self, id: &FileId) -> Result<Option<FileRecord>, RepositoryError> {
        self.as_ref().find_file(id)
    }

    fn find_file_by_content_hash(
        &self,
        content_hash: &ContentHash,
    ) -> Result<Option<FileRecord>, RepositoryError> {
        self.as_ref().find_file_by_content_hash(content_hash)
    }

    fn delete_file(&self, id: &FileId) -> Result<Option<DeletedFileRecord>, RepositoryError> {
        self.as_ref().delete_file(id)
    }

    fn list_files_recent(&self, limit: u64) -> Result<Vec<FileRecord>, RepositoryError> {
        self.as_ref().list_files_recent(limit)
    }

    fn list_files_by_tag(
        &self,
        tag: &TagKey,
        limit: u64,
    ) -> Result<Vec<FileRecord>, RepositoryError> {
        self.as_ref().list_files_by_tag(tag, limit)
    }

    fn list_tags(&self) -> Result<Vec<TagSummary>, RepositoryError> {
        self.as_ref().list_tags()
    }

    fn add_tags_to_file(
        &self,
        id: &FileId,
        tags: &[Tag],
    ) -> Result<TagMutationOutcome, RepositoryError> {
        self.as_ref().add_tags_to_file(id, tags)
    }

    fn remove_tag_from_file(
        &self,
        id: &FileId,
        tag: &TagKey,
    ) -> Result<TagMutationOutcome, RepositoryError> {
        self.as_ref().remove_tag_from_file(id, tag)
    }

    fn stats_since(&self, recent_since: UnixTimestamp) -> Result<RepositoryStats, RepositoryError> {
        self.as_ref().stats_since(recent_since)
    }

    fn pin_file(&self, id: &FileId, position: Option<u32>) -> Result<PinOutcome, RepositoryError> {
        self.as_ref().pin_file(id, position)
    }

    fn unpin_file(&self, id: &FileId) -> Result<PinOutcome, RepositoryError> {
        self.as_ref().unpin_file(id)
    }

    fn list_pinned_files(&self) -> Result<Vec<FileRecord>, RepositoryError> {
        self.as_ref().list_pinned_files()
    }

    fn reorder_pins(&self, ordered_ids: &[FileId]) -> Result<(), RepositoryError> {
        self.as_ref().reorder_pins(ordered_ids)
    }

    fn search_files(&self, query: &str) -> Result<Vec<FileRecord>, RepositoryError> {
        self.as_ref().search_files(query)
    }
}

/// Aggregate metadata counts used by health and status views.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct RepositoryStats {
    /// Total logical files.
    pub file_count: u64,
    /// Total distinct tags.
    pub tag_count: u64,
    /// Total pinned files.
    pub pinned_count: u64,
    /// Files uploaded at or after the caller-supplied recent cutoff.
    pub recent_upload_count: u64,
}

/// Tag plus the number of logical files that currently use it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TagSummary {
    /// Normalized tag display value.
    pub tag: Tag,
    /// Number of committed file records using this tag.
    pub file_count: u64,
}

/// Result of an idempotent tag mutation.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct TagMutationOutcome {
    /// Number of tag associations created or removed.
    pub changed_count: u64,
}

/// Durable result of writing a blob.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlobWriteOutcome {
    /// Content hash of the streamed bytes.
    pub content_hash: ContentHash,
    /// Opaque durable storage handle.
    pub handle: StorageHandle,
    /// Number of bytes written.
    pub size: FileSize,
    /// True when existing bytes were reused.
    pub deduplicated: bool,
}

/// Metadata needed to create a logical file record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewFileRecord {
    /// New file id.
    pub id: FileId,
    /// User-facing filename.
    pub name: FileName,
    /// Stored byte count.
    pub size: FileSize,
    /// Content hash of bytes.
    pub content_hash: ContentHash,
    /// MIME type.
    pub mime_type: MimeType,
    /// Opaque blob handle.
    pub storage_handle: StorageHandle,
    /// Upload time.
    pub uploaded_at: UnixTimestamp,
    /// Initial tags.
    pub tags: Vec<Tag>,
    /// Initial pin position.
    pub pinned_at: Option<u32>,
}

/// Result of a metadata delete transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeletedFileRecord {
    /// Record that was removed from the metadata index.
    pub record: FileRecord,
    /// Remaining logical records that still reference the same content hash.
    pub remaining_content_references: u64,
}

/// Identifier generation failure.
#[derive(Debug, Error)]
#[error("could not generate id: {message}")]
pub struct IdGenerationError {
    /// Stable diagnostic message.
    pub message: String,
}

/// Blob storage failure.
#[derive(Debug, Error)]
pub enum BlobStoreError {
    /// The storage device has insufficient free space.
    #[error(
        "insufficient storage: required {required_bytes} bytes, available {available_bytes} bytes"
    )]
    InsufficientStorage {
        /// Bytes needed to complete the write.
        required_bytes: u64,
        /// Bytes available at failure time.
        available_bytes: u64,
    },

    /// The storage backend could not read the supplied stream.
    #[error("could not read upload stream: {message}")]
    ReadFailed {
        /// Stable diagnostic message.
        message: String,
    },

    /// The storage backend could not write durable bytes.
    #[error("could not write blob: {message}")]
    WriteFailed {
        /// Stable diagnostic message.
        message: String,
    },

    /// Cleanup failed after a later application step failed.
    #[error("could not clean up unreferenced blob {handle}: {message}")]
    CleanupFailed {
        /// Opaque storage handle.
        handle: StorageHandle,
        /// Stable diagnostic message.
        message: String,
    },
}

/// Blob read failure.
#[derive(Debug, Error)]
pub enum BlobReadError {
    /// The metadata record points at a blob that no longer exists.
    #[error("blob {handle} is missing")]
    Missing {
        /// Opaque storage handle.
        handle: StorageHandle,
    },

    /// The storage backend could not open or read durable bytes.
    #[error("could not read blob: {message}")]
    ReadFailed {
        /// Stable diagnostic message.
        message: String,
    },
}

/// Metadata persistence failure.
#[derive(Debug, Error)]
pub enum RepositoryError {
    /// The repository could not acquire a write lock in time.
    #[error("metadata store is busy")]
    Busy,

    /// The repository rejected a conflicting write.
    #[error("metadata conflict: {message}")]
    Conflict {
        /// Stable diagnostic message.
        message: String,
    },

    /// The requested record does not exist.
    #[error("metadata record was not found")]
    NotFound,

    /// The repository operation failed.
    #[error("metadata operation failed: {message}")]
    OperationFailed {
        /// Stable diagnostic message.
        message: String,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn repository_error_display_messages() {
        assert_eq!(RepositoryError::Busy.to_string(), "metadata store is busy");
        assert_eq!(
            RepositoryError::NotFound.to_string(),
            "metadata record was not found"
        );
        assert_eq!(
            RepositoryError::Conflict {
                message: "dup".to_owned()
            }
            .to_string(),
            "metadata conflict: dup"
        );
        assert_eq!(
            RepositoryError::OperationFailed {
                message: "io fail".to_owned()
            }
            .to_string(),
            "metadata operation failed: io fail"
        );
    }

    #[test]
    fn blob_store_error_display_messages() {
        assert!(BlobStoreError::InsufficientStorage {
            required_bytes: 100,
            available_bytes: 10,
        }
        .to_string()
        .contains("100"));

        assert!(BlobStoreError::ReadFailed {
            message: "broken pipe".to_owned()
        }
        .to_string()
        .contains("broken pipe"));

        assert!(BlobStoreError::WriteFailed {
            message: "disk error".to_owned()
        }
        .to_string()
        .contains("disk error"));
    }

    #[test]
    fn blob_read_error_display_messages() {
        let handle = StorageHandle::new("blobs/ab/cd/test").unwrap_or_else(|e| panic!("{e}"));
        assert!(BlobReadError::Missing { handle }
            .to_string()
            .contains("missing"));

        assert!(BlobReadError::ReadFailed {
            message: "io error".to_owned()
        }
        .to_string()
        .contains("io error"));
    }

    #[test]
    fn id_generation_error_display() {
        let err = IdGenerationError {
            message: "uuid failure".to_owned(),
        };
        assert!(err.to_string().contains("uuid failure"));
    }

    #[test]
    fn repository_stats_is_constructable() {
        let stats = RepositoryStats {
            file_count: 10,
            tag_count: 3,
            pinned_count: 2,
            recent_upload_count: 5,
        };
        assert_eq!(stats.file_count, 10);
        assert_eq!(stats.pinned_count, 2);
    }

    #[test]
    fn tag_mutation_outcome_tracks_changes() {
        let outcome = TagMutationOutcome { changed_count: 3 };
        assert_eq!(outcome.changed_count, 3);
    }

    #[test]
    fn pin_outcome_tracks_state() {
        let outcome = PinOutcome {
            existed: true,
            changed: false,
        };
        assert!(outcome.existed);
        assert!(!outcome.changed);
    }

    #[test]
    fn deleted_file_record_tracks_references() {
        let id = FileId::new("del-1").unwrap_or_else(|e| panic!("{e}"));
        let name = FileName::new("gone.txt").unwrap_or_else(|e| panic!("{e}"));
        let hash =
            ContentHash::new("abcdefabcdef0123456789abcdef0123456789abcdef0123456789abcdef0123")
                .unwrap_or_else(|e| panic!("{e}"));
        let mime = MimeType::new("text/plain").unwrap_or_else(|e| panic!("{e}"));
        let handle = StorageHandle::new("blobs/ab/cd/test").unwrap_or_else(|e| panic!("{e}"));
        let ts = UnixTimestamp::new(1_700_000_000).unwrap_or_else(|e| panic!("{e}"));

        let deleted = DeletedFileRecord {
            record: FileRecord {
                id,
                name,
                size: FileSize::new(42),
                content_hash: hash,
                mime_type: mime,
                storage_handle: handle,
                uploaded_at: ts,
                tags: vec![],
                pinned_at: None,
            },
            remaining_content_references: 0,
        };
        assert_eq!(deleted.remaining_content_references, 0);
        assert_eq!(deleted.record.size.bytes(), 42);
    }
}
