//! Boundary traits between application services and infrastructure.
//!
//! Implementations live in adapter crates. Keeping these traits small and typed
//! lets tests replace `SQLite`, filesystem storage, clocks, and ID generation with
//! deterministic in-memory doubles.

use std::io::Read;

use thiserror::Error;
use tssp_domain::{
    ContentHash, FileId, FileName, FileRecord, FileSize, MimeType, SessionToken, StorageHandle,
    Tag, UnixTimestamp,
};

/// Supplies server-side UTC timestamps.
pub trait Clock {
    /// Returns the current UTC timestamp.
    fn now(&self) -> UnixTimestamp;
}

/// Generates opaque identifiers used by the system.
pub trait IdGenerator {
    /// Returns a new file identifier.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when the generator cannot produce a valid
    /// unique identifier.
    fn new_file_id(&self) -> Result<FileId, IdGenerationError>;
}

/// Generates unguessable one-time transfer tokens.
pub trait SessionTokenGenerator {
    /// Returns a new 128-bit URL-safe session token.
    ///
    /// # Errors
    ///
    /// Returns [`IdGenerationError`] when secure randomness is unavailable or
    /// generated bytes cannot be encoded into a valid token.
    fn new_session_token(&self) -> Result<SessionToken, IdGenerationError>;
}

/// Stores and retrieves content-addressed blob bytes.
pub trait BlobStore {
    /// Streams bytes into storage and returns the durable content-addressed blob.
    ///
    /// # Errors
    ///
    /// Returns [`BlobStoreError`] when the source cannot be read or the storage
    /// backend cannot durably write the blob.
    fn put_stream(&self, source: &mut dyn Read) -> Result<BlobWriteOutcome, BlobStoreError>;

    /// Removes a blob that is not referenced by committed metadata.
    ///
    /// # Errors
    ///
    /// Returns [`BlobStoreError`] when cleanup cannot be completed. Callers
    /// should log this because it may require later orphan reclamation.
    fn cleanup_unreferenced(&self, handle: &StorageHandle) -> Result<(), BlobStoreError>;
}

/// Persists and queries file metadata.
pub trait FileRepository {
    /// Inserts a logical file record for an already durable blob.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when metadata cannot be committed.
    fn insert_file(&self, new_file: NewFileRecord) -> Result<FileRecord, RepositoryError>;

    /// Returns one file record by id.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when metadata lookup fails.
    fn find_file(&self, id: &FileId) -> Result<Option<FileRecord>, RepositoryError>;

    /// Returns aggregate metadata counts for status reporting.
    ///
    /// # Errors
    ///
    /// Returns [`RepositoryError`] when aggregate queries fail.
    fn stats_since(&self, recent_since: UnixTimestamp) -> Result<RepositoryStats, RepositoryError>;
}

/// Aggregate metadata counts used by health and status views.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub struct RepositoryStats {
    /// Total logical files.
    pub file_count: u64,
    /// Total distinct tags.
    pub tag_count: u64,
    /// Total pinned files.
    pub pinned_count: u64,
    /// Files uploaded at or after the caller-supplied recent cutoff.
    pub recent_upload_count: u64,
}

/// Durable result of writing a blob.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlobWriteOutcome {
    /// Content hash of the streamed bytes.
    pub content_hash: ContentHash,
    /// Opaque durable storage handle.
    pub handle: StorageHandle,
    /// Number of bytes written.
    pub size: FileSize,
    /// True when existing bytes were reused.
    pub deduplicated: bool,
}

/// Metadata needed to create a logical file record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewFileRecord {
    /// New file id.
    pub id: FileId,
    /// User-facing filename.
    pub name: FileName,
    /// Stored byte count.
    pub size: FileSize,
    /// Content hash of bytes.
    pub content_hash: ContentHash,
    /// MIME type.
    pub mime_type: MimeType,
    /// Opaque blob handle.
    pub storage_handle: StorageHandle,
    /// Upload time.
    pub uploaded_at: UnixTimestamp,
    /// Initial tags.
    pub tags: Vec<Tag>,
    /// Initial pin position.
    pub pinned_at: Option<u32>,
}

/// Identifier generation failure.
#[derive(Debug, Error)]
#[error("could not generate id: {message}")]
pub struct IdGenerationError {
    /// Stable diagnostic message.
    pub message: String,
}

/// Blob storage failure.
#[derive(Debug, Error)]
pub enum BlobStoreError {
    /// The storage device has insufficient free space.
    #[error(
        "insufficient storage: required {required_bytes} bytes, available {available_bytes} bytes"
    )]
    InsufficientStorage {
        /// Bytes needed to complete the write.
        required_bytes: u64,
        /// Bytes available at failure time.
        available_bytes: u64,
    },

    /// The storage backend could not read the supplied stream.
    #[error("could not read upload stream: {message}")]
    ReadFailed {
        /// Stable diagnostic message.
        message: String,
    },

    /// The storage backend could not write durable bytes.
    #[error("could not write blob: {message}")]
    WriteFailed {
        /// Stable diagnostic message.
        message: String,
    },

    /// Cleanup failed after a later application step failed.
    #[error("could not clean up unreferenced blob {handle}: {message}")]
    CleanupFailed {
        /// Opaque storage handle.
        handle: StorageHandle,
        /// Stable diagnostic message.
        message: String,
    },
}

/// Metadata persistence failure.
#[derive(Debug, Error)]
pub enum RepositoryError {
    /// The repository could not acquire a write lock in time.
    #[error("metadata store is busy")]
    Busy,

    /// The repository rejected a conflicting write.
    #[error("metadata conflict: {message}")]
    Conflict {
        /// Stable diagnostic message.
        message: String,
    },

    /// The requested record does not exist.
    #[error("metadata record was not found")]
    NotFound,

    /// The repository operation failed.
    #[error("metadata operation failed: {message}")]
    OperationFailed {
        /// Stable diagnostic message.
        message: String,
    },
}
